### ISSUE TITLE
Configuring service-dns fails when installed from helm chart

### ISSUE THREAD

**Issue by seenimurugan** [hazelcast/hazelcast-kubernetes#166] opened 2019-09-10 20:51 UTC
When run the Hazelcast server using helm chart with service-dns value configured fails with the following error

Caused by: com.hazelcast.config.InvalidConfigurationException: Properties 'service-dns' and ('service-name' or 'service-label-name') cannot be defined at the same time

I override the config properties from the parent chart as follows

```
hazelcast:
  cluster:
    memberCount: 2
  service:
    clusterIP: "None"
  hazelcast:
    rest: true
    yaml:
      hazelcast:
        network:
          join:
            multicast:
              enabled: false
            kubernetes:
              enabled: true
              service-dns: ${serviceName}
        management-center:
          enabled: ${hazelcast.mancenter.enabled}
          url: ${hazelcast.mancenter.url}
```
I tried overriding the service-name property to null but it is still not working.

**Comment by mesutcelik** [comment] 2019-09-10 21:33
I tried the same and it does not work. However, when I fetched the helm chart and modified locally, `helm install .` creates correct ConfigMap.

**Comment by mesutcelik** [comment] 2019-09-10 21:45
closing. duplicate of https://github.com/hazelcast/charts/issues/58

**Closed by mesutcelik** 2019-09-10 21:45 UTC
