### ISSUE TITLE
service-dns issue, 2 kube pods are running independently and not joining/forming the hazelcast cluster

### ISSUE THREAD

**Issue by saindavs** [hazelcast/hazelcast-kubernetes#195] opened 2020-02-17 09:11 UTC
I see an issue with service-dns configuration.

I have configured 2 pods which are running the hazelcast instance in kubernetes cluster.
when the pods are started running, they are creating 2 independent hazelcast clusters (1 per jvm) and they two (2 pods in this case) together not forming the hazelcast cluster.

Pod1 logs showed 

Members {size:1, ver:1} [
	Member [15.67.7.134]:5701 - 6b335e92-8d80-4dc2-80c2-13272ecc9c63 this
]

Pod2 logs showed 

Members {size:1, ver:1} [
	Member [15.67.27.31]:5701 - 2b305c03-397f-4062-ae8f-2130f88f51c5 this
]

In the application i have the below configuration

      config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
      config.getNetworkConfig().getJoin().getKubernetesConfig().setEnabled(true)
        .setProperty("service-dns", "myapp.mynamespace.svc.cluster.local");
      HazelcastInstance hazelcastInstance = com.hazelcast.core.Hazelcast.newHazelcastInstance(config);

As they are running with the same service-dns, the above 2 pods(which has the hazelcast instance ) should form the hazelcast cluster.

The hazelcast version i am using is 3.11.2 
below is the maven dependency.

 <dependency>
        <groupId>com.hazelcast</groupId>
        <artifactId>hazelcast</artifactId>
        <version>3.11.2</version>
      </dependency>

**Comment by mesutcelik** [comment] 2020-02-17 09:23
Hi @saindavs ,

I assume you use `Deployment` instead of `StatefulSet`. It is normal for Hazelcast to start in split-brain mode as DNS records are not created when pods scheduled. 

`hazelcast.merge.first.run.delay.seconds` defaults to 300 seconds so an option is to lower that. You can also use StatefulSet not to have that issue.

A similar issue can be found here. https://github.com/hazelcast/hazelcast-kubernetes/issues/178

**Comment by saindavs** [comment] 2020-02-17 10:32
Hi @mesutcelik ,
Thanks for your quick reply.
Yes, we are using Deployment(using helm charts).

Where can i set the hazelcast.merge.first.run.delay.seconds ? i mean to which class?

in com.hazelcast.config.Config class i don't see such property.

**Comment by mesutcelik** [comment] 2020-02-17 10:39
Those are the options to set System Properties.
https://docs.hazelcast.org/docs/latest/manual/html-single/#configuring-with-system-properties

If you are using helm charts, you might want to look at Hazelcast Official Helm Charts too.
https://github.com/hazelcast/charts

**Comment by saindavs** [comment] 2020-02-17 15:30
I have configured the hazelcast.merge.first.run.delay.seconds as below, but still getting the same issue

![image](https://user-images.githubusercontent.com/28921623/74666920-68b19900-51c8-11ea-8583-24beb73c3afb.png)

**Comment by mesutcelik** [comment] 2020-02-18 07:13
Based on your configuration, If members can't create the cluster in the first place, they will wait `400` seconds to send second join request . I guess you can try to set it to zero and see if it helps.

**Comment by saindavs** [comment] 2020-02-18 10:51
Hi @mesutcelik,
I have configured the hazelcast.merge.first.run.delay.seconds to 0. But, Still the members are not forming/joining the cluster. They have started independently.

What is the best way to fix this issue?

**Comment by mesutcelik** [comment] 2020-02-18 11:20
If you can create a reproducer with all configs and a sample app in a github repository then I can have a look.

**Comment by saindavs** [comment] 2020-02-18 12:07
The Below is the only one method i am interacting with hazelcast. Please take a look. if the below code is not enough i'll create a repo and share that with you.

 @Bean
  public IMap<String, GridBucketState> getCache() {

    com.hazelcast.config.Config config = new com.hazelcast.config.Config();
    config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);

    if (CollectionUtils.isNotEmpty(appConfig.getServers())) {
      config.getNetworkConfig().getJoin().getTcpIpConfig().setEnabled(true)
          .setMembers(appConfig.getServers());
    } else {
      System.setProperty("hazelcast.merge.first.run.delay.seconds", "0");
      logger.info("service-dns value: " + appConfig.getServiceName());
      // configure kubernetes with pod labels
      config.getNetworkConfig().getJoin().getMulticastConfig().setEnabled(false);
      config.getNetworkConfig().getJoin().getKubernetesConfig().setEnabled(true)
          .setProperty("service-dns", appConfig.getServiceName());
    }
    MemoryAllocatorType allocatorType = MemoryAllocatorType.STANDARD;
    config.getNativeMemoryConfig().setEnabled(true).setAllocatorType(allocatorType)
        .setSize(new MemorySize(1, MemoryUnit.GIGABYTES));

    config.getCacheConfig("productCache").setInMemoryFormat(InMemoryFormat.BINARY)
        .setEvictionConfig(new EvictionConfig(99, EvictionConfig.MaxSizePolicy.ENTRY_COUNT,
            EvictionConfig.DEFAULT_EVICTION_POLICY));
    HazelcastInstance hazelcastInstance = com.hazelcast.core.Hazelcast.newHazelcastInstance(config);
    IMap<String, GridBucketState> map = hazelcastInstance.getMap("hazelcast-cache");
    return map;

  }

**Comment by mesutcelik** [comment] 2020-02-18 13:01
I tried myself a basic dns based discovery in minikube. It works fine if you create headless service. 
Can you try headless something similar? 
```
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-embedded
spec:
  type: ClusterIP
  clusterIP: "None"
```
Can you also post your hazelcast logs and your kubernates configs if headless does not work?

**Comment by saindavs** [comment] 2020-02-18 13:49
Hi @mesutcelik,

Thank you very much for your cooperation on this.
I have attached a log file when the hazelcast is started.
I have not configured anything on the pod configuration (deployment file)
Please let me know if you need anymore details
[app_logs.docx](https://github.com/hazelcast/hazelcast-kubernetes/files/4219544/app_logs.docx)

**Comment by mesutcelik** [comment] 2020-02-19 06:47
Can you please share how do you deploy? Without having this I can't help much. I assume you are not creating a headless service which returns SRV records of the hazelcast member pods.

**Comment by saindavs** [comment] 2020-02-19 08:41
Hi @mesutcelik,

I have attached the deployment config. 

[deploy_config.docx](https://github.com/hazelcast/hazelcast-kubernetes/files/4223938/deploy_config.docx)

**Comment by mesutcelik** [comment] 2020-02-19 08:48
Can you create one additional headless service for discovery only? Something like below.

```
apiVersion: v1
kind: Service
metadata:
  name: hazelcast-discovery
spec:
  type: ClusterIP
  clusterIP: "None"
```

Additionally, `service-dns` value that you use in hazelcast config must match to the service name you give above.

**Comment by saindavs** [comment] 2020-02-19 08:53
Hi @mesutcelik,

Sure, i will do that, But can you please tell me why should i do that? Because when i start the pod, i see both pods have hazelcast instances, The only concern is they have not formed the cluster. Do you mean with the above service it will form the cluster?

**Comment by mesutcelik** [comment] 2020-02-19 09:06
You are having an issue with discovery. Individual members will start but they can't find each other. In DNS mode, you need to use headless service because that is the only way to discovery IP addresses of other members by querying SRV records of headless service dns.
https://github.com/hazelcast/hazelcast-kubernetes#dns-lookup

Your service definition has a Service description but it is not headless and I assume it is for your Deployments so you need to have another hazelcast specific headless service for Hazelcast Discovery.

**Comment by saindavs** [comment] 2020-02-28 15:40
Hi @mesutcelik,

Instead of creating the hazelcast cluster over the application specific JVMs. is there any best way to have centralized hazelcast cluster running somewhere out side the application JVMs so that my application can connect to it and get the required from there.

Thank you.

**Comment by mesutcelik** [comment] 2020-02-28 15:51
You can use Client/Server topology to achieve what you want.

In your application JVM, you need to use hazelcast-client with hazelcast-kubernetes discovery.
You also need to deploy Hazelcast using helm chart or kubernetes operator.

https://github.com/hazelcast/hazelcast-operator
https://github.com/hazelcast/charts

**Comment by mesutcelik** [comment] 2020-03-10 20:21
I am closing this one. Please feel free to contact back if you have an issue.

**Closed by mesutcelik** 2020-03-10 20:21 UTC

**Comment by saindavs** [comment] 2020-04-07 04:12
@mesutcelik,
Thank you So much for the above information. We are going to use client server topology and see how it will work. 

Regard,
Sudhakar

**Comment by yardenshoham** [comment] 2021-05-31 12:47
@saindavs did it work out for you?
