### ISSUE TITLE
Each pod is forming its own cluster when using namespace, serviceLabelName, serviceLabelValue

### ISSUE THREAD

**Issue by kelvin-johnson** [hazelcast/hazelcast-kubernetes#113] opened 2018-11-08 15:21 UTC
I am attempting to form a cluster using embedded hazelcast while specifying a namespace, serviceLabelName and serviceLabelValue.  Below are excerpts from my code and deployment\service yaml.

Note: the K8S_NAMESPACE, K8S_SERVICE_LABEL_NAME, K8S_SERVICE_LABEL_VALUE map to the hazelcast config properties.

Each pod in the deployment forms its own cluster.  I have not found any examples that use the service label name\value and namespace.  Note that the cluster forms if you do not specify any of these properties.  Any ideas?

Hazelcast Configuration:
`@EnableHazelcastHttpSession
@Configuration
@ConfigurationProperties("kubernetes")
@Profile("k8s")
public class HazelcastConfigK8S extends AbstractHttpSessionApplicationInitializer {
    private static Logger logger = LoggerFactory.getLogger(HazelcastConfigK8S.class);

    private String namespace;
    public String getNamespace() { return namespace; }
    public void setNamespace(String namespace) { this.namespace = namespace; }

    private String serviceLabelName;
    public String getServiceLabelName() { return serviceLabelName; }
    public void setServiceLabelName(String serviceLabelName) { this.serviceLabelName = serviceLabelName; }

    private String serviceLabelValue;
    public String getServiceLabelValue() { return serviceLabelValue; }
    public void setServiceLabelValue(String serviceLabelValue) { this.serviceLabelValue = serviceLabelValue; }

    @Bean
    public HazelcastInstance hazelcastInstance() {

        logger.info("namespace: {}", namespace);
        logger.info("serviceLabelName: {}", serviceLabelName);
        logger.info("serviceLabelValue: {}", serviceLabelValue);

        MapAttributeConfig attributeConfig = new MapAttributeConfig()
                .setName(HazelcastSessionRepository.PRINCIPAL_NAME_ATTRIBUTE)
                .setExtractor(PrincipalNameExtractor.class.getName());

        Config config = new Config();
        config.getProperties().setProperty("hazelcast.discovery.enabled","true");
        JoinConfig joinConfig = config.getNetworkConfig().getJoin();
        joinConfig.getMulticastConfig().setEnabled(false);
        //joinConfig.getTcpIpConfig().setEnabled(false);

        Map<String, Comparable> props = new HashMap();
        props.put("namespace", namespace);
        props.put("service-label-name", serviceLabelName);
        props.put("service-label-value", serviceLabelValue);
        //props.put("resolve-not-ready-addresses", true);
        HazelcastKubernetesDiscoveryStrategyFactory discoveryStrategyFactory = new HazelcastKubernetesDiscoveryStrategyFactory();
        joinConfig.getDiscoveryConfig()
                .addDiscoveryStrategyConfig(new DiscoveryStrategyConfig(discoveryStrategyFactory, props));

        config.getMapConfig(HazelcastSessionRepository.DEFAULT_SESSION_MAP_NAME)
                .addMapAttributeConfig(attributeConfig)
                .addMapIndexConfig(new MapIndexConfig(
                        HazelcastSessionRepository.PRINCIPAL_NAME_ATTRIBUTE, false));

        HazelcastInstance hazelcastInstance;
        hazelcastInstance = Hazelcast.newHazelcastInstance(config);

        return hazelcastInstance;
    }`

Deployment/Service YAML:
`apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  type: LoadBalancer
  ports:
  - name: app
    port: 8080
  - name: hazelcast
    port: 5701
  selector:
    app: my-service
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: my-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-service
  minReadySeconds: 300
  template:
    metadata:
      name: my-service
      labels:
        app: my-service
    spec:
      containers:
      - name: my-service
        image: us.gcr.io/my-project/my-service:latest
        readinessProbe:
          periodSeconds: 5
          httpGet:
            path: /actuator/health
            port: 8080
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 5701
          protocol: TCP
        env:
        - name: SPRING_ACTIVE_PROFILE
          value: development, k8s
        - name: K8S_NAMESPACE
          value: my-custom-namespace
        - name: K8S_SERVICE_LABEL_NAME
          value: my-cluster-id
        - name: K8S_SERVICE_LABEL_VALUE
          value: my-uuid-value
`

**Comment by leszko** [comment] 2018-11-09 10:09
@kelvin-johnson, your Java configuration looks fine. However, the issue is in the K8 Service configuration. You don't specify any labels on the service. Please check how to do it [here](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/). You have labels on the deployment, not the service.

Actually, if you want to create a service per Hazelcast cluster, then I recommend using a service name instead of labels.

**Comment by kelvin-johnson** [comment] 2018-11-09 12:22
@leszko Thank you for your response!  What are the requirements for the labels on the service.  My understanding was that I needed to specify spec:app:myservice: some-value to tie the service to the set of pods that will be a part of the service.  

Also, there are more than just this one app that need to join this specific Hazelcast cluster.

Could you give me more detail as to what the service labels must accomplish? Or a specific example?

Thank you again!

**Comment by leszko** [comment] 2018-11-09 17:35
@kelvin-johnson Good to hear that the issue is solved. Closing it.

Btw. I think that labeling service (not the PODs) is a little confusing, so created a GH issue: #115

**Closed by leszko** 2018-11-09 17:35 UTC
Labels: question
