### ISSUE TITLE
Hazelcast issue after  enabling istio and injected  envoy

### ISSUE THREAD

**Issue by lechen26** [hazelcast/hazelcast-kubernetes#296] opened 2021-02-09 07:46 UTC
Hi

i'm having   issue with hazelcast after enabling istio and i wonder how can i address this.

i have K8s cluster and i've recently installed istio.
when trying to add envoy to deployment with hazelcast  i have a wierd issue where i have many coinnections error  during rolling upgrade. i should mention eventually the deployment is OK but  this errors indicate something is wrong.

i've noticed that without Envoy when i'm doing rolling upgrade to a deployment i see  the following:
```
[10.16.17.72]:5701 [dev] [4.0.1] Initialized new cluster connection between /10.16.17.72:45025 and /10.16.5.8:5701
[10.16.5.8]:5701 [dev] [4.0.1] Initialized new cluster connection between /10.16.5.8:5701 and /10.16.17.72:45025

[10.16.17.72]:5701 [dev] [4.0.1] Connection[id=1, /10.16.17.72:45025->/10.16.5.8:5701, qualifier=null, endpoint=[10.16.5.8]:5701, alive=false, connectionType=MEMBER] closed. Reason: Connection closed by the other side
[10.16.17.72]:5701 [dev] [4.0.1] Could not connect to: /10.16.5.8:5701. Reason: SocketException[Connection refused to address /10.16.5.8:5701]
.......
[10.16.17.72]:5701 [dev] [4.0.1] Removing connection to endpoint [10.16.5.8]:5701 Cause => java.net.SocketException {Connection refused to address /10.16.5.8:5701}, Error-Count: 5
[10.16.17.72]:5701 [dev] [4.0.1] Member [10.16.5.8]:5701 - 945ec2c8-fc56-4624-aab3-de9823d4886a is suspected to be dead for reason: No connection
```

what happens here is:
- new pod  starting  and joining the cluster. 
- connection initialize between old-pod:5701 to new-pod:xxx (2 directions)
- new pod complains it cannot reach old pod (connectionType=MEMBER) , and after 5 attempts consider it as dead and remove it from the cluster
- old pod removed once rolling upgrade completes.

now, when i'm doing the same while injecting Envoy so i have 2 containers in this pod deployment, i've noticed the following:
```
[10.16.3.244]:5701 [dev] [4.0.1] Initialized new cluster connection between /10.16.3.244:5701 and **/127.0.0.6:48287**
[10.16.5.16]:5701 [dev] [4.0.1] Initialized new cluster connection between /10.16.5.16:59827 and /10.16.3.244:5701

[10.16.5.16]:5701 [dev] [4.0.1] Connection[id=1, /10.16.5.16:59827->/10.16.3.244:5701, qualifier=null, endpoint=[10.16.3.244]:5701, alive=false, connectionType=MEMBER] closed. Reason: Connection closed by the other side
```

but then i get million of messages like the following:
```
[10.16.5.16]:5701 [dev] [4.0.1] Connection[id=2, /10.16.5.16:33659->/10.16.3.244:5701, qualifier=null, endpoint=[10.16.3.244]:5701, alive=false, connectionType=NONE] closed. Reason: Connection closed by the other side
```

the first  'Connection closed' message was MEMBER type and was on the same mentioned connection  we have  on the initializtion message (10.16.5.16:59827 --> 10.16.3.244:5701)
but the rest of the messages are  from random ports  on 10.16.5.16  to the  old pod.
i assume the reason for this is the init message the indicate `Initialized new cluster connection between /10.16.3.244:5701 and **/127.0.0.6:48287**` it configured the connection to localhost instead of to 10.16.5.16:59827.

rolling upgrade completes the same but the log is full with million of messages from that kind.

how can i prevent this ? how to make sure hazelcast  mark the connection properly between the pods ip  and not the loopback?

Thanks
Chen

**Comment by lechen26** [comment] 2021-02-09 08:25
i was  able to reproduce  it again now  but it  wasnt due to internal address  it was just mismatch.
```
I 2021-02-09T08:18:40.163Z  [10.16.5.22]:5701 [dev] [4.0.1] Initialized new cluster connection between /10.16.5.22:49213 and /10.16.5.21:5701
I 2021-02-09T08:18:40.158Z  [10.16.5.21]:5701 [dev] [4.0.1] Initialized new cluster connection between /10.16.5.21:5701 and /10.16.5.22:46274
```

why its happening? why it chose different port for the new pod ?

**Comment by hasancelik** [comment] 2021-02-09 12:20
Hi @lechen26,

With Hazelcast `4.1` release, this kind of log noises are fixed, you do not see these logs at `4.1` and `4.1.1`. Could you try to deploy newer Hazelcast versions?

Reason of `Connection closed by the other side` logs:
- Envoy proxy needs a moment to start working and a moment to stop working. Before it starts working, every connection is dropped, that is why you see the same logs while starting the cluster
- While stopping one of the member, the envoy proxy container stops working and for a moment connections to Hazelcast members are dropped and the other member tries to retries the connection that is why you see a lot of these logs.

**Comment by lechen26** [comment] 2021-02-09 13:23
Hi @hasancelik 
thanks for your response.

i dont feel its a noise. i fail to understand why the random port is not matched.
i've anyway tried your suggestion and used 4.1.1 and i get the exact same response.
```
[10.16.5.61]:5701 [dev] [4.1.1] Initialized new cluster connection between /10.16.5.61:53789 and /10.16.5.60:5701
[10.16.5.60]:5701 [dev] [4.1.1] Initialized new cluster connection between /10.16.5.60:5701 and /10.16.5.61:60942
[10.16.5.60]:5701 [dev] [4.1.1] Members {size:2, ver:2} [ Member [10.16.5.60]:5701 - 79987776-d162-48af-b630-5159f64540f7 this Member [10.16.5.61]:5701 - ac25520b-c81a-4fda-a8ed-6bde55c70da0 ]
[10.16.5.61]:5701 [dev] [4.1.1] Members {size:2, ver:2} [ Member [10.16.5.60]:5701 - 79987776-d162-48af-b630-5159f64540f7 Member [10.16.5.61]:5701 - ac25520b-c81a-4fda-a8ed-6bde55c70da0 this ]
[10.16.5.61]:5701 [dev] [4.1.1] Connection[id=1, /10.16.5.61:53789->/10.16.5.60:5701, qualifier=null, endpoint=[10.16.5.60]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
```
and then million of messages:
```
[10.16.5.61]:5701 [dev] [4.1.1] Connection[id=2, /10.16.5.61:44727->/10.16.5.60:5701, qualifier=null, endpoint=[10.16.5.60]:5701, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Exception in Connection[id=2, /10.16.5.61:44727->/10.16.5.60:5701, qualifier=null, endpoint=[10.16.5.60]:5701, alive=true, connectionType=NONE, planeIndex=-1], thread=hz.peaceful_wiles.IO.thread-in-1 java.io.IOException: Connection reset by peer
```

i expect to see connection dropped, but again for the same random port and the 5701.
on deployment without envoy i see this connection reset by peer, for connectionType=MEMBER and i see it for 5 times and then it mark the connection as dropped.

here, as mentioned i see the MEMBER type for one time and then million of messages of connectionType=NONE and multiple random ports which i assume are due to the fact the cluster initialized with wierd configuration , the unmatched ports.


any idea?

**Comment by lechen26** [comment] 2021-02-14 06:41
anything on  this? 
any help will be appriciated...

i'm just trying to understasnd if the host:port on the initialization messages should indeed be the same as i'm assuming it to be.
```
Initialized new cluster connection between /10.16.5.61:**53789** and /10.16.5.60:5701
Initialized new cluster connection between /10.16.5.60:5701 and /10.16.5.61:**60942**
```

and how  i can understand the reason for different port.
i saw on the code its being chosen by socket.getRemoteAddress 

thanks

**Comment by hasancelik** [comment] 2021-02-15 10:31
Hi @lechen26,

Actually, the TCP connection between Hazelcast nodes uses same port. The difference that you mentioned is related implementation of TCP session itself, not Hazelcast member:

> The session itself is identified by the combination of source and destination address and port. The source (client) port is usually chosen at random, while the destination (server) port is the listen port. No additional port is allocated.

https://stackoverflow.com/questions/2997754/does-the-port-change-when-a-server-accepts-a-tcp-connection

About `Reason: Connection closed by the other side` log noise, I am trying to reproduce it. I will keep you posted.

**Comment by lechen26** [comment] 2021-02-15 13:37
so seems this TCP implementation is causing me issues when envoy is in the picture.
i've just enabled debug on the code for hazelcast part and i see the attempts to create the socket connection between millions ports as mentioned.

```
D 2021-02-15T13:30:16.908Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:50205 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.907Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:53721 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.906Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:51627 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.906Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:38157 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.905Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:48313 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.903Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:35429 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.902Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:47877 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.901Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:50649 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.901Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:52135 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.899Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:57303 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.898Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:40535 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.897Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:43965 and /10.16.32.96:5701 
D 2021-02-15T13:30:16.897Z [10.16.32.139]:5701 [dev] [4.0.1] Established socket connection between /10.16.32.139:52357 and /10.16.32.96:5701 
```

not sure if i can control it.

10x

**Comment by lechen26** [comment] 2021-02-16 11:54
Ok, so i've diagnose this annoying issue further and compared the same deployment with or without envoy while debugging all logs.

seems like for a **Working** scenario we have the following situation:
[ Rolling upgrade for deployment with single pod. 
  new_pod = 10.16.6.191
  old_pod = 10.16.35.187
]
- new Pod is starting
  `[10.16.6.191]:5701 is STARTING`

- new connection between old and new pod tries to establish:
```
  [10.16.6.191]:5701 [dev] [4.1.1] Established socket connection between /10.16.6.191:36387 and /10.16.35.187:5701
  [10.16.35.187]:5701 [dev] [4.1.1] Accepting socket connection from /10.16.6.191:36387
  [10.16.35.187]:5701 [dev] [4.1.1] Established socket connection between /10.16.35.187:5701 and /10.16.6.191:36387
  [10.16.35.187]:5701 [dev] [4.1.1] Initialized new cluster connection between /10.16.35.187:5701 and /10.16.6.191:36387
  [10.16.6.191]:5701 [dev] [4.1.1] Initialized new cluster connection between /10.16.6.191:36387 and /10.16.35.187:5701
```
Explanation:
  New  pod (10.16.6.191:36387) tries to  reach  old pod (10.13.35.187)  on port 5701.
  Old pod got this  request and  accept it and  also  indicate it accept the connection from  10.16.6.191:36387
  Old pod tries to  establish connection back from his port(5701) to the  same destination he got  request from (10.16.6.191:36387).
  new cluster connection initialized from both sides  and all good.

-  old pod got shutdown hook 
```
  [10.16.35.187]:5701 [dev] [4.1.1] Running shutdown hook... Current state: ACTIVE
  [10.16.6.191]:5701 [dev] [4.1.1] Connection[id=1, /10.16.6.191:36387->/10.16.35.187:5701, qualifier=null, endpoint= 
  [10.16.35.187]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
  [10.16.6.191]:5701 [dev] [4.1.1] Could not connect to: /10.16.35.187:5701. Reason: SocketException[Connection refused to address)
  [10.16.6.191]:5701 [dev] [4.1.1] Could not connect to: /10.16.35.187:5701. Reason: SocketException[Connection refused to address)
  [10.16.6.191]:5701 [dev] [4.1.1] Could not connect to: /10.16.35.187:5701. Reason: SocketException[Connection refused to address)
  [10.16.6.191]:5701 [dev] [4.1.1] Could not connect to: /10.16.35.187:5701. Reason: SocketException[Connection refused to address)
  [10.16.6.191]:5701 [dev] [4.1.1] Could not connect to: /10.16.35.187:5701. Reason: SocketException[Connection refused to address)
  [10.16.6.191]:5701 Removing connection to endpoint [10.16.35.187]:5701 Cause => java.net.SocketException {Connection refused to address /10.16.35.187:5701}, Error-Count: 5
  [10.16.6.191]:5701 [dev] [4.1.1] Member [10.16.35.187]:5701 - a6d369e7-d628-42d8-970d-63f64898a23c is suspected to be dead for reason
```
 Explanation: 
 old pod is starting to die and we have single connection(Id=1). hazelcast  will try 5 times to connect using  that  connection 
 and  once fail will remove this member.


now, for a **NonWorking**  example. it goes like this:
[ Rolling upgrade for deployment with single pod. 
  new_pod = 10.16.6.194
  old_pod = 10.16.16.219
]

- new Pod is starting
   `[10.16.6.194]:5701 [dev] [4.1.1] [10.16.6.194]:5701 is STARTING`

- new connection between old and new pod tries to establish:
```
  [10.16.6.194]:5701 [dev] [4.1.1] Established socket connection between /10.16.6.194:53977 and /10.16.16.219:5701    
  [10.16.16.219]:5701 [dev] [4.1.1] Accepting socket connection from /127.0.0.1:58376
  [10.16.16.219]:5701 [dev] [4.1.1] Established socket connection between /127.0.0.1:5701 and /127.0.0.1:58376
  [10.16.16.219]:5701 [dev] [4.1.1] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:58376
  [10.16.6.194]:5701 [dev] [4.1.1] Initialized new cluster connection between /10.16.6.194:53977 and /10.16.16.219:5701
```
Explanation:
we can see new pod (10.16.6.194:53977) tries to connect to Old pod on port 5701
old pod got this request but identified it as it reached from envoy  (127.0.0.1:58376)
old pod now tries to establish connection from thiis 5701 port to the same destination that it got request from but makes it wrong as it tries to initialize cluster from himself to this envoy.
new  pod indicate the connection it tried to established worked properly

-  old pod got shutdown hook 
 ```
 [10.16.16.219]:5701 [dev] [4.1.1] Running shutdown hook... Current state: ACTIVE
 [10.16.16.219]:5701 [dev] [4.1.1] [10.16.16.219]:5701 is SHUTTING_DOWN
 [10.16.6.194]:5701 [dev] [4.1.1] Connection[id=1, /10.16.6.194:53977->/10.16.16.219:5701, qualifier=null, endpoint= 
 [10.16.16.219]:5701, alive=false, connectionType=MEMBER, planeIndex=0] closed. Reason: Connection closed by the other side
 [10.16.6.194]:5701 [dev] [4.1.1] Removed connection to [10.16.16.219]:5701
 [10.16.6.194]:5701 [dev] [4.1.1] Connecting to /10.16.16.219:5701, timeout: 10000, bind-any: true
 [10.16.6.194]:5701 [dev] [4.1.1] Established socket connection between /10.16.6.194:51489 and /10.16.16.219:5701
 [10.16.6.194]:5701 [dev] [4.1.1] Connection[id=2, /10.16.6.194:51489->/10.16.16.219:5701, qualifier=null, endpoint= 
 [10.16.16.219]:5701, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
 [10.16.6.194]:5701 [dev] [4.1.1] Connecting to /10.16.16.219:5701, timeout: 10000, bind-any: true
 [10.16.6.194]:5701 [dev] [4.1.1] Established socket connection between /10.16.6.194:56179 and /10.16.16.219:5701
 [10.16.6.194]:5701 [dev] [4.1.1] Connection[id=3, /10.16.6.194:56179->/10.16.16.219:5701, qualifier=null, endpoint= 
 [10.16.16.219]:5701, alive=false, connectionType=NONE, planeIndex=-1] closed. Reason: Connection closed by the other side
 ...........
```

Explanation:
old pod is starting to die , we see the first connection (ID=1) indeed marked  as connection closed for member but there i s only single attempt for  this connection.
then we have 2962 connections (ID=2 .. ID=2964) from random ports on new pod that tries to connect to the old pod on port 5701 and fail. 
after all these  messages  we finally get the eviction lines:
```
  [10.16.6.194]:5701 [dev] [4.1.1] This node does not have a connection to Member [10.16.16.219]:5701 
  [10.16.6.194]:5701 [dev] [4.1.1] Not receiving any heartbeats from Member [10.16.16.219]:5701
  [10.16.6.194]:5701 [dev] [4.1.1] Suspecting Member [10.16.16.219]:5701 
  [10.16.6.194]:5701 [dev] [4.1.1] Member [10.16.16.219]:5701 - 621e403e-950e-4ea5-a7eb-47084d1edaee is suspected to be dead
  [10.16.6.194]:5701 [dev] [4.1.1] Setting master address to [10.16.6.194]:5701
  [10.16.6.194]:5701 [dev] [4.1.1] Removing suspected address [10.16.16.219]:5701, it's no longer a member.
  [10.16.6.194]:5701 [dev] [4.1.1] Removing Member [10.16.16.219]:5701 - 621e403e-950e-4ea5-a7eb-47084d1edaee
  [10.16.6.194]:5701 [dev] [4.1.1] Members {size:1, ver:5} 
```

i think the problem was at the beginning where the  first connection between the  pods wasnt bi-directional due to the envoy.
what i fail  to understand is how does it works for other people who indicate "hazelcast works with istio without any change".

anyway to solve this?

10x

**Comment by hasancelik** [comment] 2021-02-16 15:23
Hi @lechen26,

I have tried to reproduce your issue at GKE via using [our istio guide](https://guides.hazelcast.org/istio/). It seems log noise issue does still exist(`Connection reset by peer` and `Reason: Connection closed by the other side`) for latest version(4.1.1) as well but my Hazelcast cluster could form successfully after rolling upgrade process. I do not know your setup details or how you achieve rolling upgrade(commands etc.), I can describe mines so you can compare them with yours. 

As I mentioned above, I have followed steps at our guide so only differences are I decreased [`replicas` count to `2`](https://github.com/hazelcast-guides/istio/blob/master/hazelcast-embedded/hazelcast-embedded.yaml#L7) to reduce log noise and upgrade the hazelcast version to `4.1.1` at [pom.xml](https://github.com/hazelcast-guides/istio/blob/master/hazelcast-embedded/pom.xml#L21). To reproduce your rolling upgrade process, I ran below commands for the StatefulSet:

```
$ kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
hazelcast-embedded-0   2/2     Running   0          9s
hazelcast-embedded-1   2/2     Running   0          4s

$ kubectl scale statefulset.apps/hazelcast-embedded --replicas=1

$ kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
hazelcast-embedded-0   2/2     Running   0          103s

$ kubectl scale statefulset.apps/hazelcast-embedded --replicas=2

$ kubectl get pods
NAME                   READY   STATUS    RESTARTS   AGE
hazelcast-embedded-0   2/2     Running   0          5m11s
hazelcast-embedded-1   2/2     Running   0          5m23s
```

At the end of all process, members could form a cluster:
```
...
Members {size:2, ver:2} [
	Member [10.164.0.14]:5701 - 99ed2027-2570-49c2-b131-26a786cd15f3
	Member [10.164.1.20]:5701 - 0bde9d20-79a5-49ec-9947-91eaf847dc26 this
]
....
Members {size:1, ver:3} [
	Member [10.164.1.20]:5701 - 0bde9d20-79a5-49ec-9947-91eaf847dc26 this
]
...
2021-02-16 14:28:06.898  INFO 1 --- [.IO.thread-in-0] c.h.i.server.tcp.TcpServerConnection     : [10.164.1.20]:5701 [dev] [4.1.1] Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:47024
2021-02-16 14:28:12.884  INFO 1 --- [ration.thread-0] c.h.internal.cluster.ClusterService      : [10.164.1.20]:5701 [dev] [4.1.1] 

Members {size:2, ver:4} [
	Member [10.164.1.20]:5701 - 0bde9d20-79a5-49ec-9947-91eaf847dc26 this
	Member [10.164.0.15]:5701 - 4e40afaa-d620-46ac-b328-e3968d52dede
]
```
You can find full log of first member(10.164.1.20), here [member-0.log](https://github.com/hazelcast/hazelcast-kubernetes/files/5989422/member-0.log).

About log noise issue, I will continue to investigate why it does still exist.

> what i fail to understand is how does it works for other people who indicate "hazelcast works with istio without any change".

As you can see from our guide and previously created issues at the repo, we tested Hazelcast k8s setup with Istio multiple times and we have not encountered any major issue before. Some scenarios may not have been tested by this time but that doesn't mean  "hazelcast works with istio without any change" is wrong.

**Comment by lechen26** [comment] 2021-02-16 19:30
Hi @hasancelik 

based  on your  log we have the exact same behavoir.
it also seen by the initialization message of `Initialized new cluster connection between /127.0.0.1:5701 and /127.0.0.1:47024`
dont you find it an issue that the 'connection' is between localhost while its 2  different pods? its the envoy ports not the  app.
this 'noise' of 1000 connections from random ports to the old pod, only happens when enabling istio.
if you will do the  same without  envoy you will see the  difference.

i know besides this  'noise' and the init message everything seems fine and hazelcast does switch between 1 to 2 to 1 members so they are able to join and  form a cluster.
but i dont know for  sure  if any of this will not affect other things  in prod and that's what i;m trying to understand.

do you understand why we have this 'noise' only with envoy?
did  you  understand  my comment regarding the  envoy ports?
that i think somewhere on the configuration hazelcast have partial connection ...?

10x
isnt  it the same problem?
i assume the first 'establish connection' you have is from

**Comment by lechen26** [comment] 2021-02-24 08:29
Hi

can we get help on this?
we are struggling with this for weeks now and that's the only thing that blocking us from enabling envoy istio on our production environment.

as mentioned seems like because of how envoy works and the fact it routes the requests , hazelcast noticed connection from envoy container instead of the other pod and this cause this million of warning messages.
it feels this should bee addressed on hz side, isnt it?

10x

**Comment by hasancelik** [comment] 2021-02-24 09:57
Hi @lechen26,

> do you understand why we have this 'noise' only with envoy?

As you have realized, I already described main cause of this issue at my first comment:

https://github.com/hazelcast/hazelcast-kubernetes/issues/296#issuecomment-775898082
> - Envoy proxy needs a moment to start working and a moment to stop working. Before it starts working, every connection is dropped, that is why you see the same logs while starting the cluster 
> - While stopping one of the member, the envoy proxy container stops working and for a moment connections to Hazelcast members are dropped and the other member tries to retries the connection that is why you see a lot of these logs.

I am not sure abut it should be fixed at Hazelcast IMDG core side because it's very unusual what Istio/Envoy does. Besides log noise, as you said and I tested, clustering mechanism works without any issue during RU process. 

As a temporary solution, if you don't want them in logs, just exclude them in the `logging.properties` configuration. I will talk with the team about why/how log noise is still there.

**Comment by lechen26** [comment] 2021-02-24 10:16
Thanks @hasancelik ,
i agree with you the 'clustering mechanism' seems to work but are we 100% sure its not affect anything else?
we want to test from our side an example for actual cache that needs to be preserve and see if its indeed happening, and not only counts on the 'clustering mechanism'. if that's make sense to you.

regarding your #296 comment i dont think this is the problem as mentioned.
we can set a flag for the workload to wait for the envoy to be fully operational before trying to start the application container, and i already tested it. it didnt solve this issue and we will get these messages.
(proxy.istio.io/config: ‘{ “holdApplicationUntilProxyStarts”: true }’)

as mentioned the issue is that hazelcast indicate the connection and initialize the cluster based on the origin, and it mark the origin as itself cause it got it from the envoy from his prespective.
thats why it seems like there is a map or something of connections on hazelcast and one  of them is a bad one which caused all of these warnings until the pod dies.
excluding connection errors from the logging properties sounds like a real bad option:\

to be honest i'm still not sure we are on the same page on that manner...
as again i dont think its a 'noise' its a false connection...
maybe it does not affect the joining processes but it still an issue.

thanks
Chen

**Comment by alparslanavci** [comment] 2021-02-26 16:31
@lechen26, it looks like the connection retry logs you've seen are rooted in Hazelcast's failure detector mechanism. 

Firstly, Hazelcast has built-in failure detectors to determine if a member in the cluster is unreachable or crashed. Please see their details [here](https://docs.hazelcast.com/imdg/latest/clusters/failure-detector-configuration.html).

Now let me try to tell what happened step by step:

1. The first Hazelcast member (A) initializes. 
2. The second Hazelcast member (B) initializes and A & B form a cluster together.
3. Both A & B start their failure detectors in the background, by sending heartbeats.
4. A dies, but B doesn't directly know about it (most likely because of the Envoy proxy). B still assumes that A is alive. Thus, it still tries to send heartbeats.
5. When B sends a heartbeat to A, it tries to get the existing connection or creates a new one (see [here](https://github.com/hazelcast/hazelcast/blob/master/hazelcast/src/main/java/com/hazelcast/internal/cluster/impl/ClusterHeartbeatManager.java#L650)). 
6. Since the connection is already closed, B tries to create a new one each time it sends a heartbeat. But it cannot since A is dead. Because of this retries, you see lots of connection retry logs.
7. After some point, B decides A is dead since B cannot connect to A. At this point, you see the following log:
```
[10.164.1.20]:5701 [dev] [4.1.1] Suspecting Member [10.164.0.14]:5701 - 99ed2027-2570-49c2-b131-26a786cd15f3 because it has not sent any heartbeats since 2021-02-16 14:24:36.963. Now: 2021-02-16 14:25:41.325, heartbeat timeout: 60000 ms, suspicion level: 1.00
[10.164.1.20]:5701 [dev] [4.1.1] Member [10.164.0.14]:5701 - 99ed2027-2570-49c2-b131-26a786cd15f3 is suspected to be dead for reason: Suspecting Member [10.164.0.14]:5701 - 99ed2027-2570-49c2-b131-26a786cd15f3 because it has not sent any heartbeats since 2021-02-16 14:24:36.963. Now: 2021-02-16 14:25:41.325, heartbeat timeout: 60000 ms, suspicion level: 1.00
```
As you can notice, there are no connection retry logs after this point. 

As @hasancelik mentioned, this process is expected and has no effect on regular cluster operations.

Please let us know if you have further questions.

**Comment by lechen26** [comment] 2021-02-28 10:55
Hi @alparslanavci ,

thanks for your response.
I totally understand the flow, and your step-by-step explanation is exactly what i understood from this process.

the thing is, this is the same flow with or without envoy right?
the difference is, without envoy , pod A tries to connect to pod B (with the one and only connection id=1), undertsand it dead after 5 attempts and remove it from cluster.
with envoy, pod A tries to connect to pod B (with 2000 connections) until the pod is eventually removed from the cluster.

i still believe the problem is on the way the connection is mark and should be handled differently when using envoy.
the fact hazelcast member indicate the envoy he was the destination that tries to establish a connection with it and not the original pod is a problem,  but to be honest not sure how i can convince you guys with more information then i've already provided.

assuming we want to ignore this , i'm not sure how we should handle this.
everytime hazelcast pods will be restarted our logs will be filled with this messages. ignoring connections issue globally?
excluding them means we will ignore another real issue if we will have any.

10x

**Comment by alparslanavci** [comment] 2021-03-01 13:26
@lechen26 I'll dig a bit deeper on this issue and share my findings here. Please stay tuned.

**Comment by alparslanavci** [comment] 2021-03-02 00:41
@lechen26, I checked Hazelcast internals and extracted a bug. Please follow it up here: https://github.com/hazelcast/hazelcast/issues/18320

The issue doesn't cause any problems on Hazelcast's cluster formation or regular operations as I tested, but it needs to be fixed since the member opens unnecessary connections when running behind a proxy. 

Thanks for your contribution, and also patience.

**Comment by lechen26** [comment] 2021-03-02 07:38
@alparslanavci exactly, thanks a lot!

**Comment by Holmistr** [comment] 2021-05-19 14:15
@alparslanavci The related Hazelcast bug was resolved: https://github.com/hazelcast/hazelcast/issues/18320 
Should we close this one as well?

**Comment by alparslanavci** [comment] 2021-06-22 11:42
I can verify that this issue is fixed by https://github.com/hazelcast/hazelcast/issues/18320. 

However, when using Hazelcast behind a proxy, the users can still face some connection errors on member disconnection. This is caused by the proxy and Hazelcast containers' startup latencies. The proxy (Envoy) continues to listen to the port and accept TCP connections even if the Hazelcast instance is not ready, which makes other Hazelcast members to connect & disconnect momentarily until the Hazelcast instance is up and running. This is expected, and not affecting Hazelcast's lifecycle directly.

Closing this one as the main issue is fixed.

**Closed by alparslanavci** 2021-06-22 11:42 UTC
