### ISSUE TITLE
What is the difference between Native Java and REST client of hazelcast. I created a map with same name using both clients. I saved key-value pair A in the map using  java client and key-value pair B using rest client. My question is if hazelcast cluster is same then why can't I get key-value pair B using java client and vice-versa.

### ISSUE THREAD

**Issue by AayushiKhandelwal123** [hazelcast/hazelcast-kubernetes#286] opened 2020-12-21 17:44 UTC

**Comment by hasancelik** [comment] 2020-12-22 10:14
Hi @AayushiKhandelwal123,

I have made quick local test and I could not reproduce your issue with Hazelcast `4.1`. Probably you have misconfigured something, could you describe more your setup or provide reproducer. Here is the my local steps:

1. Start HZ server:
```
public class Server {
    public static void main(String[] args) throws IOException {
        Config config = new Config();
        config.getNetworkConfig().getRestApiConfig().setEnabled(true).enableGroups(RestEndpointGroup.DATA);
        Hazelcast.newHazelcastInstance(config);
    }
}

....
INFO: [192.168.1.89]:5701 [dev] [4.1] 

Members {size:1, ver:1} [
	Member [192.168.1.89]:5701 - 9c4ad0b2-c45d-4a7b-bf09-d91f3c5b0a34 this
]
....
```
2. Put entry into map via using REST client:
```
curl -v -H "Content-Type: text/plain" -d "bar" http://192.168.1.89:5701/hazelcast/rest/maps/test/foo

------
....
< HTTP/1.1 200 OK
< Content-Length: 0
...
```

3. Check map size via using Java Client:
```
public class Client {
    public static void main(String[] args) {
        HazelcastInstance client = HazelcastClient.newHazelcastClient();
        IMap<String, String> map = client.getMap("test");
        System.out.println(map.size());
        client.shutdown();
    }
}

-------
...
Members [1] {
	Member [192.168.1.89]:5701 - 9c4ad0b2-c45d-4a7b-bf09-d91f3c5b0a34
}
Map size: 1
....
```

BTW, your issue is not related to hazelcast-kubernetes plugin itself so I am closing this one. Could you use [our community slack channel](https://slack.hazelcast.com/) to ask question or create an issue at main [hazelcast repo](https://github.com/hazelcast/hazelcast).

**Closed by hasancelik** 2020-12-22 10:14 UTC
